Lanchonete/Models/Enums.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Lanchonete.Models {
    public class Enums {
        
        public enum ETipoPromocao {
            [Display(Name = "Nenhuma")]
            Nenhuma,
            [Display(Name = "Light")]
            Light,
            [Display(Name = "Muita Carne")]
            MuitaCarne,
            [Display(Name = "Muito Queijo")]
            MuitoQueijo
        }

        public enum ETipoAlimento {
            Carne,
            Queijo,
            Vegetal,
            Outros
        }
    }
}

Lanchonete/Models/Ingrediente.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Lanchonete.Models.Enums;

namespace Lanchonete.Models {
    public class Ingrediente {

        public uint Id { get; set; }
        public string Nome { get; set; }
        public decimal Valor { get; set; }
        public int Quantidade { get; set; }
        public ETipoAlimento Tipo { get; set; }

        public Ingrediente() { Quantidade = 1; }

        public Ingrediente Clone() {
            return new Ingrediente {
                Id = this.Id,
                Nome = this.Nome,
                Valor = this.Valor,
                Quantidade = this.Quantidade,
                Tipo = this.Tipo
            };
        }
    }
}

Lanchonete/Models/Lanche.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using static Lanchonete.Models.Enums;

namespace Lanchonete.Models {
    public class Lanche {

        public uint Id { get; set; }
        public string Nome { get; set; }
        public List<Ingrediente> Ingredientes { get; set; }
        public List<string> PromocoesAtivas = new List<string>();

        public decimal Valor {
            get {

                decimal valorTotalIngredientes = 0.0m;
                Ingredientes.ForEach(i => valorTotalIngredientes += i.Valor * i.Quantidade);

                return valorTotalIngredientes;
            }
        }

        public decimal ValorDesconto {
            get {
                return CalcularDesconto();
            }
        }

        public decimal ValorTotal {
            get {
                return Valor - ValorDesconto;
            }
        }

        public Lanche Clone() {
            return new Lanche {
                Id = this.Id,
                Nome = this.Nome,
                Ingredientes = this.Ingredientes,
                PromocoesAtivas = this.PromocoesAtivas
            };
        }

        public decimal CalcularDesconto() {
            decimal desconto = 0;
            PromocoesAtivas.Clear();

            // Desconto promoção Muita Carne
            Ingredientes.ForEach(i => {
                if (i.Tipo == ETipoAlimento.Carne && i.Quantidade >= 3) {
                    desconto += i.Valor * (i.Quantidade / 3);
                    if (!PromocoesAtivas.Any(p => p == "Muita Carne")) PromocoesAtivas.Add("Muita Carne");
                }
            });

            // Desconto promoção Muito Queijo
            Ingredientes.ForEach(i => {
                if (i.Tipo == ETipoAlimento.Queijo && i.Quantidade >= 3) {
                    desconto += i.Valor * (i.Quantidade / 3);
                    if (!PromocoesAtivas.Any(p => p == "Muito Queijo")) PromocoesAtivas.Add("Muito Queijo");
                }
            });

            // Desconto promoção Light
            if (Ingredientes.Any(i => i.Nome == "Alface")
                && !Ingredientes.Any(i => i.Nome == "Bacon")) {
                desconto = Valor * 0.1m; //10% de desconto no valor total do lanche
                PromocoesAtivas.Add("Light");
            }

            return desconto;
        }
    }
}

Lanchonete/Models/Pedido.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lanchonete.Models {
    public class Pedido {

        public uint Id { get; set; }
        public List<Lanche> Lanches { get; set; }

        public decimal ValorTotal {
            get {
                decimal valorTotalLanches = 0.0m;
                Lanches.ForEach(i => valorTotalLanches += i.ValorTotal);

                return valorTotalLanches;
            }
        }

        public Pedido() { Lanches = new List<Lanche>(); }
    }
}

Lanchonete/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace Lanchonete.Controllers {

    public class HomeController : Controller {

        public IActionResult Index() {
            return View();
        }

        //public IActionResult About()
        //{
        //    ViewData["Message"] = "Your application description page.";

        //    return View();
        //}

        //public IActionResult Contact()
        //{
        //    ViewData["Message"] = "Your contact page.";

        //    return View();
        //}

        public IActionResult Error() {
            return View();
        }
    }
}

Lanchonete/Controllers/PedidoController.cs
using Lanchonete.BLL;
using Lanchonete.Models;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lanchonete.Controllers
{
    public class PedidoController : Controller
    {
        public IActionResult Index() {

            var pedidoBLL = new PedidoBLL();
            var listaPedidos = pedidoBLL.GetListaPedidos();

            return View(listaPedidos);
        }

        public IActionResult Criar() {

            var lancheBLL = new LancheBLL();
            var listaLanches = lancheBLL.GetListaLanches();

            var ingredientesBLL = new IngredienteBLL();
            ViewBag.ListaIngredientes = ingredientesBLL.GetListaIngredientes();

            return View(listaLanches);
        }

        [HttpGet]
        public JsonResult ActionGetLanche(int idLanche) {
            var lancheBLL = new LancheBLL();

            return Json(new {
                success = true,
                lanche = lancheBLL.GetLanche(idLanche)
            });
        }

        [HttpPost]
        public JsonResult ActionCalcularDescontoLanche(Lanche lanche) {
            var lancheBLL = new LancheBLL();
            var ingredienteBLL = new IngredienteBLL();

            var novoLanche = lancheBLL.GetLanche(lanche.Nome);
            novoLanche.Ingredientes.Clear();

            // Adiciona os ingredientes de acordo com o "banco de dados" por segurança
            lanche.Ingredientes.ForEach(i => {
                var ingrediente = ingredienteBLL.GetIngrediente(i.Nome);
                ingrediente.Quantidade = i.Quantidade;
                novoLanche.Ingredientes.Add(ingrediente);
            });
            novoLanche.CalcularDesconto();

            return Json(new {
                success = true,
                lanche = novoLanche
            });
        }

        public JsonResult ActionCriarPedido(List<Lanche> lanchesPedido) {

            var lancheBLL = new LancheBLL();
            var ingredienteBLL = new IngredienteBLL();

            Pedido novoPedido = new Pedido();

            foreach (var lanche in lanchesPedido) {

                var novoLanche = lancheBLL.GetLanche(lanche.Nome);
                novoLanche.Ingredientes.Clear();

                // Adiciona os ingredientes de acordo com o "banco de dados" por segurança
                lanche.Ingredientes.ForEach(i => {
                    var ingrediente = ingredienteBLL.GetIngrediente(i.Nome);
                    ingrediente.Quantidade = i.Quantidade;
                    novoLanche.Ingredientes.Add(ingrediente);
                });

                novoLanche.CalcularDesconto();
                novoPedido.Lanches.Add(novoLanche);
            }

            var pedidoBLL = new PedidoBLL();
            pedidoBLL.SalvarPedido(novoPedido);

            return Json(new { success = true });
        }

    }
}

Lanchonete/Controllers/PromocaoController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Lanchonete.BLL;
using Lanchonete.Models;

namespace Lanchonete.Controllers {

    public class PromocaoController : Controller {

        public IActionResult Index() {

            var lancheBLL = new LancheBLL();
            var listaLanches = lancheBLL.GetListaLanches();

            ViewBag.PromocoesList = Enum.GetValues(typeof(Enums.ETipoPromocao)).Cast<Enums.ETipoPromocao>().ToList();
            
            return View(listaLanches);
        }

        [HttpPost]
        public JsonResult ActionAlterarPromocaoLanche(int idLanche, string nomePromocao) {

            //var lancheBLL = new LancheBLL();
            //lancheBLL.SetPromocaoLanche(idLanche, nomePromocao);

            return Json(new {
                success = true
            });
        }
    }
}

Lanchonete/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Lanchonete";
}

<div class="row">
    <div class="col-md-5">
        <h2>Areas Administrativas</h2>
        <ul>
            @*<li><a asp-area="" asp-controller="Promocao" asp-action="Index">Gerenciar Promoções</a></li>*@
            <li><a asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a></li>
        </ul>
    </div>
    <div class="col-md-5">
        <h2>Areas Usuários</h2>
        <ul>
            <li><a asp-area="" asp-controller="Pedido" asp-action="Criar">Criar Pedido</a></li>
        </ul>
    </div>
</div>

Lanchonete/Views/Pedido/Criar.cshtml
@using Lanchonete.Models
@model List<Lanche>
@{
    ViewData["Title"] = "Criar Pedido";
}
@section Scripts {
    <script type="text/javascript">
        var URLActionGetLanche = "@Url.Action("ActionGetLanche")";
        var URLActionCalcularDescontoLanche = "@Url.Action("ActionCalcularDescontoLanche")";
        var URLActionCriarPedido = "@Url.Action("ActionCriarPedido")";
        var DadosIngredientes = @Json.Serialize(ViewBag.ListaIngredientes);
        var LanchesTabela = new Object();
        var LancheAtual = new Object();
    </script>
    <script src="~/js/pedido/criarPedido.js" asp-append-version="true"></script>
}

<h1>Criar Pedido</h1>

<div style="display: flex; margin-top: 20px">
    <label>Adicionar Lanche: </label>
    <select id="lanchesSelect" class="form-control" style="margin-left: 15px; margin-right: 15px">
        @foreach(var lanche in Model) {
            <option value="@lanche.Id">@lanche.Nome</option>
        }
    </select>
    <button class="btn btn-info" onclick="AdicionarLancheListaPedido()">Adicionar lanche</button>
</div>

<div id="divListaLanches" style="margin-top: 20px">
    <table class="table">
        <thead>
            <tr><th>Lanches</th></tr>
            <tr>
                <th />
                <th>Nome</th>
                <th style="width: 50%">Ingredientes</th>
                <th>Desconto</th>
                <th>Valor Total</th>
                <th />
            </tr>
        </thead>
        <tbody id="tBodyListaLanches">
            <tr>
                <td>Não há lanches adicionados</td>
            </tr>
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3" />
                <th>Valor Total Pedido:</th>
                <td id="tdValorTotalPedido"> R$0.00</td>
            </tr>
        </tfoot>
    </table>
    <button class="btn btn-success" onclick="CriarPedido()">Criar Pedido</button>
</div>

<!-- Modal -->
<div id="myModal" class="modal fade" role="dialog">
    <div class="modal-dialog">

        <!-- Modal content-->
        <div class="modal-content">
            <div class="modal-header">
                <button type="button" class="close" data-dismiss="modal">&times;</button>
                <h4 class="modal-title">Ingredientes</h4>
            </div>
            <div class="modal-body">
                <div style="display: flex; width: 720px">
                    <label>Adicionar Ingrediente</label>
                    <select id="selectIngrediente" class="form-control">
                        @foreach (var ingrediente in ViewBag.ListaIngredientes) {
                            <option value="@ingrediente.Nome" selected>@ingrediente.Nome - R$@ingrediente.Valor</option>
                        }
                    </select>
                    <button id="btnAdicionarIngrediente" class="btn btn-info" onclick="adicionarIngrediente()">Adicionar Ingrediente</button>
                </div>
                <div>
                    <table class="table">
                        <thead>
                            <tr>
                                <th />
                                <th>Nome</th>
                                <th>Quantidade</th>
                            </tr>
                        </thead>
                        <tbody id="tBodyListaIngredientes">

                        </tbody>
                    </table>
                </div>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            </div>
        </div>

    </div>
</div>

Lanchonete/Views/Pedido/Index.cshtml
@using Lanchonete.Models
@model List<Pedido>
@{
    ViewData["Title"] = "Lanchonete - Listagem Pedidos";
}

<h1>Listagem Pedidos</h1>

<div>
    <table id="tableListaPedidos" class="table">
        <thead>
            <tr>
                <th>Pedidos</th>
            </tr>
            <tr>
                <th>Número Pedido</th>
                <th>Lanches</th>
                <th>Valor</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var pedido in Model) {
                <tr id="@pedido.Id">
                    <td>@pedido.Id</td>
                    <td>@string.Join(", ", pedido.Lanches.Select(l => l.Nome))</td>
                    <td>@pedido.ValorTotal.ToString("R$ ##.##")</td>
                </tr>
            }
        </tbody>
    </table>
</div>

Lanchonete/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lanchonete</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">Lanchonete</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    @*<li><a asp-area="" asp-controller="Promocao" asp-action="Index">Gerenciar Promoções</a></li>*@
                    <li><a asp-area="" asp-controller="Pedido" asp-action="Index">Pedidos</a></li>
                    <li><a asp-area="" asp-controller="Pedido" asp-action="Criar">Criar Pedido</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - Lanchonete</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>